#!/usr/bin/env ruby

# Adds the ticket id if the branch is named something like this:
# branch_name_4354363

# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

commit_msg = File.read(ARGV[0])
branch = `git rev-parse --abbrev-ref HEAD`

b = branch[/-[a-z0-9]{7}$/i]
ticket_id ||= b && b[1..-1]
ticket_id ||= branch[/(?:[A-Z]+-)?\d+$/]
ticket_id ||= branch[%r{^[a-z]+/(\d+)}]

if ticket_id
  new_commit_msg = "#{commit_msg.strip} ##{ticket_id}\n"
  File.write(ARGV[0], new_commit_msg)
end
